export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ"
export const PRODUCT_LIST_REQ_SUCCESS = "PRODUCT_LIST_REQ_SUCCESS"
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_REQ_FAIL"



export const PRODUCT_DETAIL_REQ = "PRODUCT_DETAIL_REQ"
export const PRODUCT_DETAIL_REQ_SUCCESS = "PRODUCT_DETAIL_REQ_SUCCESS"
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_DETAIL_REQ_FAIL"